openapi: 3.0.0
info:
  title: Module 2
  description: Module CRUD APIs Documentation
  version: 1.0.0
servers:
  - url: http://localhost:5858
paths:
  /api/sensorData:
    get:
      summary: Get a list of tasks
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/sensorData'
        '404':
          description: Route not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error404'
        '500':
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sensorData500'
    post:
      summary: Create a sensor data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createSensorDataBody'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Data successfully created!
        '404':
          description: Route not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error404'
        '500':
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sensorData500'

  
components:
  schemas:
    error404:
      type: object
      properties:
        errorMessage: 
          type: string
          example: /route not found
    sensorData:
      type: object
      properties: 
        code:
          type: integer
          example: 200
        message:
          type: string
          example: Data retrieved!
        data:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
                example: 65349abcc764a2b949dd4f53
              location:
                type: string
                example: Location2
              temperature_celsius:
                type: number
                format: float
                example: 20.5431121531523
              humidity_percent:
                type: integer
                example: 32
              pressure_hpa:
                type: integer
                example: 1003
    sensorData500:
      type: object
      properties:
        message:
          type: string
        stackTrace:
          type: string
    createSensorDataBody:
      type: object
      properties:
        location:
          type: string
          example: Location2
          required: true
        temperature_celsius:
          type: number
          format: float
          required: true
          example: 20.5431121531523
        humidity_percent:
          type: integer
          required: true
          example: 32
        pressure_hpa:
          type: integer
          required: true
          example: 1003
